version: '3'

services:
  ethereum:
    build:
      context: .
      dockerfile: ./ethereum/Dockerfile
    ports:
      - "8545:8545"

  contract_deployer:
    build:
      context: ./solidity
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_0

  peggy_0:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_0:/root/home
    depends_on:
      - ethereum
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  orchestrator_0:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_0
    environment:
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_PHRASE=${COSMOS_PHRASE}
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
      - COSMOS_RPC=${COSMOS_RPC}
      - COSMOS_GRPC=${COSMOS_GRPC}
      - ETH_RPC=${ETH_RPC}
      - DENOM=${DENOM}
      - CONTRACT_ADDR=${CONTRACT_ADDR}

  peggy_1:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_1:/root/home
    depends_on:
      - ethereum
      - peggy_0

  orchestrator_1:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_1
    environment:
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_PHRASE=${COSMOS_PHRASE}
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
      - COSMOS_RPC=${COSMOS_RPC}
      - COSMOS_GRPC=${COSMOS_GRPC}
      - ETH_RPC=${ETH_RPC}
      - DENOM=${DENOM}
      - CONTRACT_ADDR=${CONTRACT_ADDR}

  peggy_2:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_2:/root/home
    depends_on:
      - ethereum
      - peggy_0

  orchestrator_2:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_2
    environment:
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_PHRASE=${COSMOS_PHRASE}
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
      - COSMOS_RPC=${COSMOS_RPC}
      - COSMOS_GRPC=${COSMOS_GRPC}
      - ETH_RPC=${ETH_RPC}
      - DENOM=${DENOM}
      - CONTRACT_ADDR=${CONTRACT_ADDR}

  peggy_3:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_3:/root/home
    depends_on:
      - ethereum
      - peggy_0

  orchestrator_3:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_3
    environment:
      - COSMOS_KEY=${COSMOS_KEY}
      - COSMOS_PHRASE=${COSMOS_PHRASE}
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
      - COSMOS_RPC=${COSMOS_RPC}
      - COSMOS_GRPC=${COSMOS_GRPC}
      - ETH_RPC=${ETH_RPC}
      - DENOM=${DENOM}
      - CONTRACT_ADDR=${CONTRACT_ADDR}