version: '3'

services:
  ethereum:
    image: ethereum/client-go:stable

  contract_deployer:
    build:
      context: ./solidity
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_0

  orchestrator_0:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_0

  peggy_0:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_0:/root/home
    depends_on:
      - ethereum

  peggy_1:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_1:/root/home
    depends_on:
      - ethereum
      - peggy_0

  peggy_2:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_2:/root/home
    depends_on:
      - ethereum
      - peggy_0

  peggy_3:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_3:/root/home
    depends_on:
      - ethereum
      - peggy_0