version: '3'

services:
  ethereum:
    image: ethereum/client-go:stable

  orchestrator_a:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
    depends_on:
      - ethereum
      - peggy_0

  peggy_0:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_0:/root/home

  peggy_1:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_1:/root/home

  peggy_2:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_2:/root/home

  peggy_3:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    volumes:
      - ./testdata/testchain/peggy_3:/root/home
