version: '3'
#-p 9090:9090 -p 26657:26657 -p 1317:1317

services:
  peggy:
    build:
      context: ./module
      dockerfile: ./Dockerfile
    ports:
      - "26656:26656"
      - "26657:26657"

  ethereum:
    build:
      context: ./solidity
      dockerfile: ./Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30304:30304"

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: ./Dockerfile
